export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',

  FORBIDDEN: 'FORBIDDEN',
  STAFF_ASSIGNMENT_REQUIRED: 'STAFF_ASSIGNMENT_REQUIRED',
  STAFF_SHIFT_INACTIVE: 'STAFF_SHIFT_INACTIVE',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  TICKET_INVALID_STATE: 'TICKET_INVALID_STATE',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  PAYMENT_NOT_CONFIRMED: 'PAYMENT_NOT_CONFIRMED',

  LIVE_NOT_OPEN: 'LIVE_NOT_OPEN',
  LIVE_ACCESS_DENIED: 'LIVE_ACCESS_DENIED',
  LIVE_CODE_INVALID: 'LIVE_CODE_INVALID',
  LIVE_TOKEN_EXPIRED: 'LIVE_TOKEN_EXPIRED',
  LIVE_TOKEN_INVALID: 'LIVE_TOKEN_INVALID',
  LIVE_TOKEN_USED: 'LIVE_TOKEN_USED',

  CONNECTION_BLOCKED: 'CONNECTION_BLOCKED',
  CONNECTION_ALREADY_EXISTS: 'CONNECTION_ALREADY_EXISTS',

  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
