const ORG_ROLES = Object.freeze({
  ORG_ADMIN: 'ORG_ADMIN',
  TECH_ADMIN: 'TECH_ADMIN',
  OPS_FINANCE: 'OPS_FINANCE',
  CX_RESEARCH: 'CX_RESEARCH',
  CITY_OPS: 'CITY_OPS',
  STAFF: 'STAFF',
});

const EVENT_ROLES = Object.freeze({
  EVENT_LEAD: 'EVENT_LEAD',
  MARSHAL: 'MARSHAL',
  VOLUNTEER: 'VOLUNTEER',
  HOST: 'HOST',
});

const STAFF_PERMISSIONS = Object.freeze({
  EVENT_READ: 'EVENT_READ',
  EVENT_MANAGE: 'EVENT_MANAGE',
  CHECKIN_SCAN: 'CHECKIN_SCAN',
  LIVE_OPEN_CLOSE: 'LIVE_OPEN_CLOSE',
  LIVE_SUSPEND_USER: 'LIVE_SUSPEND_USER',
  SAFETY_READ: 'SAFETY_READ',
  SAFETY_RESPOND: 'SAFETY_RESPOND',
  ATTENDEE_REMOVE: 'ATTENDEE_REMOVE',
  REFUND_MANAGE: 'REFUND_MANAGE',
  STAFF_MANAGE: 'STAFF_MANAGE',
});

module.exports = { ORG_ROLES, EVENT_ROLES, STAFF_PERMISSIONS };
